Update DG, relating to Lesson
AY2122S1-CS2103T-F13-3/tp pull request #133
Opened 2021-10-14 08:23 UTC by eeliana

2021-10-15 03:20 UTC, eeliana commented
@Chesterwongz @angkoonhwee Update the diagrams in the DG to include the new logic from scheduling and undoRedo

2021-10-17 04:52 UTC, Chesterwongz requested changes

2021-10-17 04:52 UTC, Chesterwongz commented on docs/DeveloperGuide.md
> +| L1  | `HIGH`   | user                                       | add recurring lessons for a student                                 | keep track of the regular lessons
The numbering is off?

2021-10-18 02:07 UTC, Chesterwongz approved these changes
LGTM

2021-10-18 02:07 UTC, merged