Fix Undo/Redo Bugs
AY2122S1-CS2103T-F13-3/tp pull request #276
Opened 2021-10-30 17:36 UTC by angkoonhwee

- [x] Remains on filtered list after every command except add command #267 #240 #251 #259 
- [x] Undo and Redo will not mix up lists #259 #265 #265 
- [x] Detailed Messages of which command type was undone for which student #129

**Note:**
I don't quite get the implementation of `LessonEditTest#execute_filteredList_success`  but it is not passing. What happens now is that the expectedModel's filteredList is the unfilteredList whereas the actual model's filteredList is just the filtered student.
The thing is I am not sure where in the code was the model filtered.

2021-10-30 17:45 UTC, angkoonhwee commented
@eeliana You might want to explain the `LessonEditCommandTest#execute_filteredList_success` to me so that I can change accordingly. Seems like the expectedModel is the one that is weird.

2021-10-31 02:13 UTC, eeliana commented
> @eeliana You might want to explain the `LessonEditCommandTest#execute_filteredList_success` to me so that I can change accordingly. Seems like the expectedModel is the one that is weird.

You have to add `showPersonAtIndex(expectedModel, INDEX_FIRST_PERSON);` after expectedModel.setPerson... because now the list no longer goes back to unfiltered state after execution.

2021-10-31 04:05 UTC, lingshanng commented
I found a bug. Given a list of 4 students
1. delete 4
2. undo
3. delete 4
4. redo

cannot redo 1. because only 3 students

2021-10-31 04:16 UTC, lingshanng commented
Also, when you undo a command for a person not currently in the filtered list, the student's lessons appear at the side bar, even if it's not lesson command but a student command.

Eg.
1. edit Alex
2. Filter list without Alex
3. undo
-> Alex's lessons appear at the side

![image](https://user-images.githubusercontent.com/35279431/139567366-2aa59a6b-b552-42ed-841f-f7d27070cbf1.png)

2021-10-31 16:12 UTC, Chesterwongz reviewed
I think only undoable commands show clear the undostack. Right now if i do this:
1. edit person
2. undo
3. `calendar`
4. redo
Result is no commands to redo, instead of redoing edit person

2021-11-01 05:55 UTC, Xiaoyunnn commented on src/main/java/seedu/address/logic/commands/UndoCommand.java
> +        if (studentModified != null && !model.getFilteredPersonList().contains(studentModified)) {
maybe can create another method in model to make `!model.getFilteredPersonList().contains(studentModified)` obey SLAP

2021-11-01 06:01 UTC, Xiaoyunnn reviewed
I think it looks ok now, just need to specify clearly when can undo/redo command in ug, cus its a bit confusing now

2021-11-01 06:06 UTC, Xiaoyunnn commented
small cosmetic issue:
1. delete 3 (charlotte)
2. undo (selects Charlotte's card)
3. redo (delete Charlotte, selects the prev student Bernice's card, but lesson panel shows generic student lesson list)
![image](https://user-images.githubusercontent.com/76084739/139628712-8b31df5d-60b4-4902-86ae-839a68166c74.png)

can make it not select prev person's card?

2021-11-02 05:37 UTC, Chesterwongz commented
> cosmetic issue/bug(?):
> 
> 1. delete 3 (charlotte)
> 2. undo (selects Charlotte's card)
> 3. redo (delete Charlotte, selects the prev student Bernice's card, but lesson panel shows generic student lesson list, and when u click bernice’s card, it doesn't show bernice’s lessons)
>    ![image](https://user-images.githubusercontent.com/76084739/139628712-8b31df5d-60b4-4902-86ae-839a68166c74.png)
> 
> can make it not select prev person's card?

Fixed in #279

2021-11-02 05:38 UTC, Chesterwongz approved these changes
LGTM

2021-11-02 09:02 UTC, Xiaoyunnn approved these changes
LGTM

2021-11-02 12:19 UTC, lingshanng commented
Can I just check are these behaviours intended?

Add person & edit person -> doesn't select person and view lessons
Filter list and edit person -> goes back to full list

2021-11-02 13:51 UTC, angkoonhwee commented
@lingshanng For point 2, I think that was the initial implementation of AB3 I don't think anyone changed it, but it would make more sense to stay on the list? I can change that while I am at it. As for point 1, I am not sure who implemented the command result thingy so it might have be intended. I personally think that selecting the add/edited student makes more sense and if it is agreeable I can also change that while I am at it.

2021-11-02 13:59 UTC, eeliana commented
> @lingshanng For point 2, I think that was the initial implementation of AB3 I don't think anyone changed it, but it would make more sense to stay on the list? I can change that while I am at it. As for point 1, I am not sure who implemented the command result thingy so it might have been intended. I personally think that selecting the add/edited student makes more sense and if it is agreeable I can also change that while I am at it.

Just have to add toAdd and personAfterEdit to the CommandResult returned for AddCommand and EditCommand. I think we discussed in tele before.

2021-11-02 14:01 UTC, eeliana requested changes
Can add changes suggested, thanks for the hardwork!

2021-11-02 16:06 UTC, lingshanng approved these changes

2021-11-03 01:32 UTC, merged