CS2101 UG improvements
AY2122S1-CS2103T-F13-3/tp pull request #376
Opened 2021-11-06 15:18 UTC by Chesterwongz

2021-11-06 15:28 UTC, Xiaoyunnn commented on docs/UserGuide.md
> +  e.g. in `add n/NAME`, `NAME` is a parameter that can be substituted as `add n/John Doe`.
emm "`NAME` is a parameter that can be substituted..." sounds like substituting just the NAME but the eg included the prefix as well
```suggestion
  e.g. in `add n/NAME`, `NAME` is a parameter that can be substituted with `John Doe`.
```

2021-11-06 15:28 UTC, Xiaoyunnn commented on docs/UserGuide.md
>  * `add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01 pp/92345678 pe/jackdoe@example.com sch/John's School stream/John stream lvl/J1`
```suggestion
* `add n/John Doe p/98765432 e/johnd@gmail.com a/Sengkang Ave 2, Block 123, #02-01 pp/92345678 pe/jackdoe@gmail.com sch/Seng Kang Secondary School stream/O-Level stream lvl/S1` Adds a `S1` student named `John Doe` who is studying `O-Level` at `Seng Kang Secondary School` and lives at `Sengkang Ave 2, Block 123, #02-01`, with phone number `98765432`, email `johnd@gmail.com`, parent contact number `92345678` and parent email `jackdoe@gmail.com`.
```
CS2103 website say example need to be sound like rl example. Not sure if the additional explanation is too lengthy.. But other examples have additional desc

2021-11-06 15:28 UTC, Xiaoyunnn commented on docs/UserGuide.md
> +* `add n/Betsy Crowe t/new a/Newgate p/91234567 r/Remember to get school and academic level! t/missinginfo`
need add desc for this eg?

2021-11-11 08:20 UTC, eeliana commented on docs/UserGuide.md
> +  TAB will help you with these constraints through a message in the UI if you give an invalid input.
```suggestion
  TAB will help you with these constraints by displaying relevant messages to you if you give an invalid input.
```

2021-11-11 08:23 UTC, eeliana requested changes

2021-11-11 08:23 UTC, eeliana commented on docs/UserGuide.md
> +Help is just a moment away when you use TAB.
Strange

2021-11-11 08:23 UTC, eeliana commented on docs/UserGuide.md
> +Need to update lesson information? This command allows you to do just that.
Do the same for the rest of the commands as well. Otherwise, not very consistent in tone. If not, I think its fine to leave it as the original one

2021-11-11 13:19 UTC, angkoonhwee commented on docs/UserGuide.md
> +title: The Ultimate User Guide to the Tuition Address Book (TAB)
Sir this is a bit too long particularly the navbar

2021-11-11 13:19 UTC, angkoonhwee commented on docs/UserGuide.md
> +The more you use TAB, the more useful it becomes.
This line probably don't need right

2021-11-11 14:46 UTC, lingshanng commented on docs/UserGuide.md
> +   ![start](images/start.png) <br> _How TAB looks when you start it for the first time._
can you use `<div class="caption">...</div>`

2021-11-11 14:46 UTC, lingshanng commented on docs/UserGuide.md
> +There will also be links in relevant places to help you navigate the document
```suggestion
There will also be links in relevant places to help you navigate the document.
```

2021-11-11 14:46 UTC, lingshanng commented on docs/UserGuide.md
> +TAB is a Command-line Interface (CLI) app, meaning that you tell TAB what to do using commands in the form of lines of texts.
```suggestion
TAB is a Command-line Interface (CLI) app, meaning that you tell TAB what to do using commands in the form of lines of text.
```

2021-11-11 14:46 UTC, lingshanng commented on docs/UserGuide.md
> +6. If you wish to clear the sample data and start using the app, simply type `clear` and press enter.
wrap enter in <kbd>
```suggestion
6. If you wish to clear the sample data and start using the app, simply type `clear` and press enter.
```

2021-11-11 14:46 UTC, lingshanng commented on docs/UserGuide.md
> +* Extraneous parameters for commands that do not take in parameters (such as `help`, `list`, `calendar`, `exit`, `clear`, etc.) are not valid.<br>
why the extra comma?

2021-11-11 14:46 UTC, lingshanng commented on docs/UserGuide.md
> +Format: `edit INDEX [n/NAME] [a/ADDRESS] [p/PHONE] [e/EMAIL] [pp/PARENT_PHONE_NUMBER] [pe/PARENT_EMAIL] [sch/SCHOOL] [stream/ACAD_STREAM] [lvl/ACAD_LEVEL] [r/REMARK] [t/TAG]…​`
why got two format

2021-11-11 14:51 UTC, lingshanng commented on docs/UserGuide.md
> +Suppose we want to update Betsy Crowe with her school and academic level, and remove her remarks and tags.
```suggestion
Suppose you want to update Betsy Crowe with her school and academic level, and remove her remarks and tags.
```

2021-11-11 15:09 UTC, angkoonhwee commented on docs/UserGuide.md
> +The features are categorised as follows:
```suggestion
The features are categorised as follow:
```

2021-11-11 15:10 UTC, angkoonhwee commented on docs/UserGuide.md
> -This section explains the command format used for TAB's commands.<br/>
I feel like we can leave this here? General overview of the section is clearer isn't it？

2021-11-11 15:15 UTC, angkoonhwee commented on docs/UserGuide.md
> -This section briefly explains the various section of TAB's GUI.
I assuming this can be add back?

2021-11-11 15:23 UTC, Chesterwongz commented on docs/UserGuide.md
> +* Extraneous parameters for commands that do not take in parameters (such as `help`, `list`, `calendar`, `exit`, `clear`, etc.) are not valid.<br>
grammerly say one

2021-11-11 15:58 UTC, angkoonhwee approved these changes

2021-11-11 15:58 UTC, eeliana approved these changes

2021-11-11 16:14 UTC, merged